### ISSUE TITLE
Can you add the support of encryption context 

### ISSUE THREAD

**Issue by onion1984** [aws/aws-nitro-enclaves-sdk-c#143] opened 2024-10-21 13:22 UTC
The current parameters of the kms-tool doesn't have support for encryption context 
https://docs.aws.amazon.com/kms/latest/developerguide/encrypt_context.html

Can you add the support for this parameter?

**Comment by jplock** [comment] 2024-10-21 13:48
Duplicate of #35 ?

**Comment by onion1984** [comment] 2024-10-21 13:52
yes, it is a duplicate of #35. Customer has already on boarded nitro enclave, this is the last hurdle before they go for fully production

**Comment by atanzu** [comment] 2024-12-12 13:02
Pull requests #145 and #146 added new APIs:
* from #145: `aws_kms_decrypt_blocking_from_request` and` aws_kms_encrypt_blocking_from_request` which allow to pass user-prepared `aws_kms_encrypt_request` or` aws_kms_decrypt_request` structs.
* from #146: `aws_kms_decrypt_blocking_with_context` and `aws_kms_encrypt_blocking_from_request` which are similar to `aws_kms_encrypt_blocking`/`aws_kms_decrypt_blocking` but allow to pass a string with a JSON containing the Encryption context.

These new APIs should be sufficient to consider this issue as resolved.

**Closed by atanzu** 2024-12-12 13:02 UTC
